on:
    push:

jobs:
    build-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Cache Docker images.
          uses: ScribeMD/docker-cache@0.3.7
          with:
            key: docker-${{ runner.os }}
        - run: docker build --tag my-image .
    build-cache-manual:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: docker build --tag my-image --cache-to type=gha --cache-from type=gha .